Add mass pruneable blocks
enjin/platform-core pull request #137
Opened 2024-02-26 03:51 UTC by enjinabner

2024-02-26 10:08 UTC, v16Studios requested changes
Great work :)  Most of the PR suggestions that were generated all look sensible to me, maybe get them in too 👍🏻

2024-02-27 05:21 UTC, enjinabner commented
> Great work :) Most of the PR suggestions that were generated all look sensible to me, maybe get them in too 👍🏻

> Avoid unnecessary database interaction by returning an empty query when pruning is disable

This suggestion was not implemented, because of how the trait was coded

2024-02-27 13:10 UTC, leonardocustodio approved these changes

2024-02-27 16:27 UTC, v16Studios approved these changes

2024-02-27 21:56 UTC, merged